version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongovolume:/var/lib/mongodb/data
  fastcontainer:
    image: fastapi
    ports:
      - 8000:8000  
volumes:
  mongovolume: {}